### ISSUE TITLE
Documentation for Reduction

### ISSUE THREAD

**Issue by bringhurst** [hpc/libcircle#24]
Not sure how to do this yet to make it easy for beginners -- just creating this issue for future reference.

**Comment by adammoody** [comment]
Documented reduction API in README: https://github.com/hpc/libcircle/commit/aae3ad77f257da623be9476be1771d6f3f8a22be

**Comment by adammoody** [comment]
@spakin , I realize this response is a tad tardy :-)  FYI, your reduction code is just fine actually.  However, the period between reductions is hard-coded to 10 seconds, and the libcircle job must run for long enough for one period to expire to execute the first reduction.  I'll try to document that detail in the README.

**Comment by spakin** [comment]
@adammoody: Thanks for the clarification (both here and in the README).  Would it be possible also to have the reduction trigger as part of `CIRCLE_finalize()`?  That should make the reduction semantics a bit less unintuitive.

**Comment by adammoody** [comment]
@spakin , good suggestion.  That will ensure it fires at least once, and it also guarantees a reduction with the final result.  I'll look at adding that.

**Comment by adammoody** [comment]
@spakin , the library now calls the reduction after the work loop terminates: https://github.com/hpc/libcircle/commit/a2c0d37500c659c9423d99725d7cf6f227c551e1

Thanks for the suggestion.

**Comment by spakin** [comment]
@adammoody: Cool; thanks for implementing that.
